The purpose of this algorithm is to take an image and play around with it. Then the new images can be taken and put through the Google Cloud Platform AutoML Beta for image classification 

In [152]:
# Importing of libraries used 
import matplotlib
import sys
import random
import numpy as np
import PIL
 
# Convert Image to array
img = PIL.Image.open(r"G:\My Drive\CATSVDOGS2.0\test1\1.jpg")
a = numpy.array(img)
print(a)
 
# Convert array to Image
img = PIL.Image.fromarray(a)
img.show()

[[[ 37  64  94]
  [ 35  62  92]
  [ 34  60  93]
  ...
  [ 71 108 199]
  [ 49  86 175]
  [ 48  85 173]]

 [[ 41  68  98]
  [ 39  66  96]
  [ 37  63  96]
  ...
  [ 71 106 198]
  [ 48  85 174]
  [ 47  84 172]]

 [[ 45  72 102]
  [ 43  70 100]
  [ 40  66  99]
  ...
  [ 70 105 199]
  [ 48  83 173]
  [ 47  83 171]]

 ...

 [[165 169 170]
  [167 171 174]
  [171 174 179]
  ...
  [ 97  89  70]
  [ 85  77  54]
  [ 87  77  52]]

 [[168 172 173]
  [169 173 176]
  [172 175 180]
  ...
  [116 108  89]
  [105  97  74]
  [108  98  73]]

 [[173 177 178]
  [172 176 179]
  [172 175 180]
  ...
  [125 117  98]
  [115 107  84]
  [118 108  83]]]


In [153]:
# This will transpose the initial array, then shuffle the columns (now in row form thanks to the transpose).
# Then finally it converts it back to its original form with the shuffle performed

a=np.transpose(a)
np.random.shuffle(a)
a=np.transpose(a)
print(a)

[[[ 94  64  37]
  [ 92  62  35]
  [ 93  60  34]
  ...
  [199 108  71]
  [175  86  49]
  [173  85  48]]

 [[ 98  68  41]
  [ 96  66  39]
  [ 96  63  37]
  ...
  [198 106  71]
  [174  85  48]
  [172  84  47]]

 [[102  72  45]
  [100  70  43]
  [ 99  66  40]
  ...
  [199 105  70]
  [173  83  48]
  [171  83  47]]

 ...

 [[170 169 165]
  [174 171 167]
  [179 174 171]
  ...
  [ 70  89  97]
  [ 54  77  85]
  [ 52  77  87]]

 [[173 172 168]
  [176 173 169]
  [180 175 172]
  ...
  [ 89 108 116]
  [ 74  97 105]
  [ 73  98 108]]

 [[178 177 173]
  [179 176 172]
  [180 175 172]
  ...
  [ 98 117 125]
  [ 84 107 115]
  [ 83 108 118]]]


In [154]:
# Transform Matrix 
b = np.random.randint(1,3,size=(499,381,3))

In [155]:
# Check to see if it matches with a
print(b)
print(b.shape)

[[[1 2 2]
  [2 1 1]
  [2 2 1]
  ...
  [1 2 1]
  [2 2 2]
  [2 2 1]]

 [[1 1 2]
  [1 2 1]
  [2 1 2]
  ...
  [2 1 1]
  [2 1 1]
  [1 1 2]]

 [[1 1 2]
  [1 1 2]
  [1 1 2]
  ...
  [2 1 1]
  [1 1 2]
  [2 1 1]]

 ...

 [[1 2 2]
  [2 1 2]
  [2 1 2]
  ...
  [2 2 1]
  [1 2 1]
  [1 1 1]]

 [[1 1 2]
  [2 1 2]
  [2 1 1]
  ...
  [1 2 1]
  [2 2 2]
  [2 1 2]]

 [[1 2 1]
  [1 2 1]
  [2 1 2]
  ...
  [2 2 1]
  [1 1 2]
  [2 2 2]]]
(499, 381, 3)


In [156]:
# Output matrix: empty array of same dimensions as a and b
c = np.zeros(shape=(499,381,3))

In [157]:
# Checks if correct
print(c)
print(c.shape)

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 ...

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]
(499, 381, 3)


In [158]:
# Convert array to Image
img = PIL.Image.fromarray(a)
img.show()

So the code ends up being able to shuffle the matrix and spit back out an image. This only shuffles the RGB values however and does not move the pixels around.

Below I will take my first image in the CATDOG dataset and jumble it. It will then save into a new folder and show the result.. However this will not be consistent across a dataset as it jumbles the image differently every time

In [159]:
BLOCKLEN = 30 # Adjust and be careful here. The higher the value the less jumbled the image becomes... and vice-versa!
img = PIL.Image.open(r"G:\My Drive\CATSVDOGS2.0\test1\1.jpg")
width, height = img.size
xblock = width / BLOCKLEN
yblock = height / BLOCKLEN
blockmap = [(xb*BLOCKLEN, yb*BLOCKLEN, (xb+1)*BLOCKLEN, (yb+1)*BLOCKLEN) 
            for xb in range(int(xblock)) for yb in range(int(yblock))]
shuffle = list(blockmap)
random.shuffle(shuffle)
result = Image.new(img.mode, (width, height))
for box, sbox in zip(blockmap, shuffle):
    c = img.crop(sbox)
    result.paste(c, box)
#result.save(r"G:\My Drive\CATSVDOGS2.0\test1\00000000001.jpg")
result.show()